// V2 Mock Data — 3 projects × 3~4 goals × 6~8 work cards
// Tags, labels and copy all in English.

import { Evidence } from './types';

export type CardStatus = 'in_progress' | 'completed' | 'blocked';

export interface CardData {
  id: string;
  title: string;
  summary: string;
  content: string;
  result: string;
  mindsetTags: string[];
  toolTags: string[];
  created_at: string;
  status: CardStatus;
  category?: string;
  judgment?: string | { ai?: string; builder?: string; why?: string };
  evidence?: Evidence[];
  images?: string[];
}

export interface GoalData {
  id: string;
  title: string;
  description: string;
  cards: CardData[];
}

export interface ProjectData {
  id: string;
  title: string;
  description: string;
  goals: GoalData[];
}

export interface MockPortfolioV2 {
  tagCategories: { [category: string]: string[] };
  projects: ProjectData[];
}

export const tagCategories: { [category: string]: string[] } = {
  mindset: ['Cost Awareness', 'Validation Discipline', 'Autonomous Execution', 'Self-Error Correction', 'Execution over Docs'],
  tool: ['claude code', 'Next.js', 'Supabase', 'PostgreSQL', 'vLLM', 'Playwright', 'lm-eval-harness', 'Docker', 'Redis', 'LoRA', 'end-to-end'],
};

export const mockPortfolioV2: MockPortfolioV2 = {
  tagCategories,
  projects: [
    {
      id: 'project-bd-v2',
      title: "Builder's Diary V2",
      description: 'Automated portfolio recording system — redesigned UI and agent integration',
      goals: [
        {
          id: 'goal-ui-redesign',
          title: 'UI Layout Redesign',
          description: '3-zone layout: goal list + card timeline + detail panel',
          cards: [
            {
              id: 'card-1',
              title: 'Searchable Filter Bar (Project / Goal)',
              summary: 'Dropdown + keyword search for fast project and goal switching',
              content: 'Added two searchable dropdowns below the header for project and goal selection. Typing narrows candidates in real time; selecting immediately refreshes the card list. The goal dropdown is scoped to the selected project.',
              result: 'With 3 projects and 10 goals, typing 2 characters narrows candidates to 1–2 — confirmed.',
              mindsetTags: ['Validation Discipline', 'Autonomous Execution'],
              toolTags: ['Next.js'],
              created_at: '2026-09-04',
              status: 'in_progress',
              category: 'Engineering',
              judgment: {
                ai: 'Proposed a single combined search box covering both projects and goals',
                builder: 'Rejected it — split into two scoped dropdowns instead',
                why: 'scoping the goal list to the chosen project is what makes 2-char narrowing work',
              },
              evidence: [
                { type: 'artifact', label: 'PR #42 — FilterBar component', url: 'https://github.com/example/builders-diary/pull/42', meta: '+210 −34, 4 files' },
                { type: 'quote', label: 'test output', quote: '12 passed, 0 failed' },
                { type: 'input', label: 'Original 3-zone layout spec', meta: 'design-doc.md' },
              ],
            },
            {
              id: 'card-2',
              title: 'Left Goal List Component',
              summary: 'Vertical goal list for the selected project; click to filter cards',
              content: 'Goals are stacked vertically in a fixed-width left column, each with a card-count badge. Clicking changes selectedGoalId, which is shared with the top dropdown.',
              result: 'Clicking a goal leaves only its cards in the center area — flow verified.',
              mindsetTags: ['Execution over Docs'],
              toolTags: ['Next.js'],
              created_at: '2026-09-04',
              status: 'in_progress',
            },
            {
              id: 'card-3',
              title: 'Center Card Scroll Area (Horizontal)',
              summary: 'Cards scroll horizontally; front face shows title only',
              content: 'Cards are laid out with flex-row + overflow-x-auto and scroll-snap. The front face exposes only title, tags, and status to speed up scanning. Scrollbar minimised to 3 px.',
              result: 'Horizontal scroll and snap work correctly with 8+ cards; no conflict with vertical scroll.',
              mindsetTags: ['Validation Discipline'],
              toolTags: ['Next.js'],
              created_at: '2026-09-03',
              status: 'completed',
              evidence: [{ label: 'Loom walkthrough', url: 'https://loom.com/share/example', type: 'loom' }],
            },
            {
              id: 'card-4',
              title: 'Right Detail Panel',
              summary: 'Click a card to show title, summary, detail, result, and tags in the right panel',
              content: 'Clicking a card opens a detail panel on the right showing the work detail and result. A close button restores the card area to full width.',
              result: 'Card click → panel open → close → width restore round-trip verified.',
              mindsetTags: ['Cost Awareness'],
              toolTags: ['Next.js'],
              created_at: '2026-09-03',
              status: 'completed',
            },
            {
              id: 'card-5',
              title: 'Responsive Layout (Tablet / Mobile)',
              summary: 'Reflow the 3-zone layout as a stacked structure on narrow screens',
              content: 'Below lg, the goal list collapses. Below md, the detail panel drops to a bottom sheet. Horizontal card scroll is preserved on touch.',
              result: 'Layout intact and cards reachable at 768 px and 480 px viewports.',
              mindsetTags: ['Self-Error Correction', 'Execution over Docs'],
              toolTags: ['Next.js'],
              created_at: '2026-09-02',
              status: 'in_progress',
            },
            {
              id: 'card-6',
              title: 'Dark Theme Token Cleanup',
              summary: 'Consolidate #0e0e0e / #4ade80 palette into CSS variables',
              content: 'Scattered hardcoded colours were moved to :root variables; all components now reference var() only. Accent colour converges on a single token.',
              result: 'Zero hardcoded colour strings remaining — confirmed via grep.',
              mindsetTags: ['Validation Discipline'],
              toolTags: ['Next.js'],
              created_at: '2026-09-01',
              status: 'completed',
            },
            {
              id: 'card-7',
              title: 'Onboarding Screen Rewrite',
              summary: 'Show only the connect button and 3-step guide before folder is linked',
              content: 'The pre-connection state is split into its own screen. Three cards guide: create or connect a folder, connect MCP, then call the skill from an agent chat.',
              result: 'Onboarding renders without portfolio; main view renders after connection — toggled and confirmed.',
              mindsetTags: ['Autonomous Execution', 'Execution over Docs'],
              toolTags: ['claude code'],
              created_at: '2026-09-04',
              status: 'in_progress',
              evidence: [
                { label: 'Design doc', url: 'https://notion.so/example', type: 'doc' },
                { label: 'PR #48', url: 'https://github.com/example/builders-diary/pull/48', type: 'github' },
              ],
            },
          ],
        },
        {
          id: 'goal-state-mgmt',
          title: 'State Management',
          description: 'Centralise project / goal / card selection state and sync with storage',
          cards: [
            {
              id: 'card-8',
              title: 'Centralise Selection State',
              summary: 'Manage project / goal / card selection in one place and propagate via props',
              content: 'selectedProjectId, selectedGoalId, and selectedRecordId are lifted to the top-level container. Children receive them as props only. Filter logic is derived via useMemo.',
              result: 'Changing the project resets goal and card selection as expected.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['Next.js'],
              created_at: '2026-09-03',
              status: 'completed',
            },
            {
              id: 'card-9',
              title: 'Auto-refresh Cards on Filter Change',
              summary: 'Recompute cards whenever project, goal, tags, or keyword changes',
              content: 'filteredRecords is wrapped in a useMemo with four dependencies (project, goal, tags, keyword). When no goal is selected, all project cards are shown flat.',
              result: 'Each filter — alone and combined — reflects immediately in the card list.',
              mindsetTags: ['Validation Discipline'],
              toolTags: ['Next.js'],
              created_at: '2026-09-02',
              status: 'completed',
            },
            {
              id: 'card-10',
              title: 'localStorage State Restore',
              summary: 'Preserve the last project and goal selection across page refreshes',
              content: 'Selection state is serialised to localStorage and restored on mount. If a stored id is missing from current data, it falls back to the first item.',
              result: 'Last selection restored after refresh; missing id falls back safely.',
              mindsetTags: ['Self-Error Correction', 'Cost Awareness'],
              toolTags: ['Next.js'],
              created_at: '2026-09-02',
              status: 'blocked',
            },
            {
              id: 'card-11',
              title: 'URL Query String Sync',
              summary: 'Reflect selection state in URL for shareable deep links',
              content: 'project, goal, and record are encoded in the query string and parsed on entry to set initial state. Back navigation is consistent.',
              result: 'Deep-link entry selects the correct project, goal, and card on render.',
              mindsetTags: ['Validation Discipline'],
              toolTags: ['Next.js', 'end-to-end'],
              created_at: '2026-09-01',
              status: 'in_progress',
            },
            {
              id: 'card-12',
              title: 'TypeScript Type Definitions',
              summary: 'Lock down Record / Goal / Project / Portfolio and tag category types',
              content: 'Data model consolidated in types.ts; mindsetTags, toolTags, and result fields added. Parser and mock data share the same types.',
              result: 'Zero type errors on tsc project build.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['Next.js'],
              created_at: '2026-09-01',
              status: 'completed',
              evidence: [{ label: 'types.ts diff', url: 'https://github.com/example/builders-diary/commit/abc123', type: 'github' }],
            },
            {
              id: 'card-13',
              title: 'Filter Reset Rules',
              summary: 'Clear downstream selection when folder is reconnected or project changes',
              content: 'Rules for clearing goal, card, and keyword on any upstream change are consolidated in one place, preventing stale selections that would render an empty card list.',
              result: 'No previous goal filter lingers after switching projects.',
              mindsetTags: ['Self-Error Correction'],
              toolTags: ['Next.js'],
              created_at: '2026-08-31',
              status: 'in_progress',
            },
          ],
        },
        {
          id: 'goal-testing',
          title: 'Testing & Performance',
          description: 'Measure filter and scroll performance; catch regressions automatically',
          cards: [
            {
              id: 'card-14',
              title: 'Filter Performance Benchmark',
              summary: 'Measure filter response time against 1000 cards',
              content: 'Filter recomputation time was measured with and without useMemo on 1000 synthetic cards. The bottleneck was the tag-matching loop.',
              result: 'After memoisation: recomputation 12 ms → 2 ms (console timing).',
              mindsetTags: ['Cost Awareness', 'Validation Discipline'],
              toolTags: ['Next.js'],
              created_at: '2026-09-02',
              status: 'completed',
            },
            {
              id: 'card-15',
              title: 'Virtual Scroll Investigation',
              summary: 'Render only visible cards when the list grows large',
              content: 'Investigated a windowing library for 200+ cards. Judged over-engineering for the current scale (65 cards) and deferred.',
              result: '65 cards render at 60 fps without windowing — decision recorded.',
              mindsetTags: ['Self-Error Correction', 'Cost Awareness'],
              toolTags: ['Next.js'],
              created_at: '2026-09-01',
              status: 'blocked',
            },
            {
              id: 'card-16',
              title: 'E2E Test: Filter Flow',
              summary: 'Automate project → goal → card click → detail verification',
              content: 'Scripted the core flow with Playwright: dropdown search input, goal selection, card click, detail panel text assertion.',
              result: 'Core flow e2e test is green and reproducible in CI.',
              mindsetTags: ['Execution over Docs', 'Validation Discipline'],
              toolTags: ['Playwright', 'end-to-end'],
              created_at: '2026-09-01',
              status: 'in_progress',
              evidence: [{ label: 'CI run', url: 'https://github.com/example/builders-diary/actions/runs/12345', type: 'github' }],
            },
            {
              id: 'card-17',
              title: 'Empty State Rendering',
              summary: 'Different messages when all cards are filtered out vs. no cards exist',
              content: 'Two empty states are distinguished: filter returned zero results vs. project has no cards. Each shows different copy with a reset button.',
              result: 'Both empty states show correct copy and reset button.',
              mindsetTags: ['Self-Error Correction'],
              toolTags: ['Next.js'],
              created_at: '2026-08-31',
              status: 'completed',
            },
            {
              id: 'card-18',
              title: 'Production Build Regression Gate',
              summary: 'Require next build to pass before every commit',
              content: 'Type check, lint, and static generation are run together as a build gate. Enforced locally before each commit.',
              result: 'next build: Compiled successfully / 4 static pages.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['Next.js', 'Docker'],
              created_at: '2026-08-30',
              status: 'completed',
            },
            {
              id: 'card-19',
              title: 'Keyboard Navigation (Accessibility)',
              summary: 'Tab and Enter to move between and open cards',
              content: 'Cards now have tabindex and a key handler so Enter opens the detail panel. Focus ring is shown in accent colour.',
              result: 'Tab → Enter opens detail panel without mouse — confirmed.',
              mindsetTags: ['Self-Error Correction'],
              toolTags: ['Next.js'],
              created_at: '2026-08-29',
              status: 'in_progress',
            },
          ],
        },
        {
          id: 'goal-mcp',
          title: 'MCP Server Integration',
          description: 'Auto-populate records via @skill calls from any agent chat',
          cards: [
            {
              id: 'card-20',
              title: 'Switch to MCP stdio Server',
              summary: 'Replace the Flask HTTP wrapper with standard MCP stdio protocol',
              content: 'Removed the HTTP wrapper and rewrote as an MCP stdio server. Tool list and input schema are exposed per spec.',
              result: 'Three tools visible and callable in MCP Inspector.',
              mindsetTags: ['Execution over Docs', 'Validation Discipline'],
              toolTags: ['claude code', 'Docker'],
              created_at: '2026-09-04',
              status: 'completed',
              evidence: [{ label: 'MCP server repo', url: 'https://github.com/example/builders-diary-mcp', type: 'github' }],
            },
            {
              id: 'card-21',
              title: '@builders-diary Skill Call Convention',
              summary: 'Trigger record creation by calling the skill from chat',
              content: 'Defined a skill trigger so calling @builders-diary in Claude or Cursor produces one record from the current session trace.',
              result: 'Sample session → skill call → one markdown entry created in entries/.',
              mindsetTags: ['Autonomous Execution', 'Execution over Docs'],
              toolTags: ['claude code'],
              created_at: '2026-09-04',
              status: 'in_progress',
            },
            {
              id: 'card-22',
              title: 'Front-matter Parser Robustness',
              summary: 'Stable parsing of YAML front matter into Record',
              content: 'Missing required fields and inconsistent tag array notation are handled defensively. Failed files are skipped with a log rather than crashing.',
              result: 'Missing-field sample is skipped without crash.',
              mindsetTags: ['Validation Discipline', 'Self-Error Correction'],
              toolTags: ['claude code'],
              created_at: '2026-09-03',
              status: 'in_progress',
            },
            {
              id: 'card-23',
              title: 'Folder Scan → Portfolio Tree',
              summary: 'Walk content/projects-*/goals/*/records and build the 3-level tree',
              content: 'File System Access API iterates the folder to build project → goal → record. Permission prompts and reconnection are handled.',
              result: 'Sample folder scan → 3-level tree constructed and verified.',
              mindsetTags: ['Autonomous Execution'],
              toolTags: ['Next.js', 'end-to-end'],
              created_at: '2026-09-02',
              status: 'in_progress',
            },
            {
              id: 'card-24',
              title: 'Docker Image Minimisation',
              summary: 'Strip unnecessary dependencies from the MCP server image',
              content: 'Switched to a slim base image and multi-stage build, copying only build artefacts.',
              result: 'Image size reduced; stdio startup confirmed.',
              mindsetTags: ['Cost Awareness', 'Self-Error Correction'],
              toolTags: ['Docker'],
              created_at: '2026-09-01',
              status: 'completed',
            },
            {
              id: 'card-25',
              title: 'Deployment Pipeline Audit',
              summary: 'Walk the full path from skill call to web card end-to-end',
              content: 'Manually stepped through: chat skill call → markdown created → folder scan → web card visible.',
              result: 'Sample record appeared as a web card — full path succeeded once.',
              mindsetTags: ['Execution over Docs', 'Autonomous Execution'],
              toolTags: ['end-to-end', 'Docker'],
              created_at: '2026-08-30',
              status: 'blocked',
            },
          ],
        },
      ],
    },
    {
      id: 'project-supabase-cost',
      title: 'Supabase Cost Optimisation',
      description: 'Measure and reduce public board egress and DB operating costs',
      goals: [
        {
          id: 'goal-cost-tracking',
          title: 'Cost Tracking System',
          description: 'Instrument egress per service and track the residual',
          cards: [
            {
              id: 'card-26',
              title: 'Egress Meter via httpx Hook',
              summary: 'Log egress_mb per run using a Python client hook',
              content: 'An httpx hook sums response bytes per run and writes egress_mb to run_log. Browser requests are architecturally invisible and this is documented in the docstring.',
              result: '91 [EGRESS] log lines captured; pipeline total 1,225 MB aggregated.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['Supabase', 'PostgreSQL'],
              created_at: '2026-09-02',
              status: 'completed',
              evidence: [{ label: 'egress_meter.py', url: 'https://github.com/example/gstack/blob/main/egress_meter.py', type: 'github' }],
            },
            {
              id: 'card-27',
              title: 'Residual Tracking: 14% Measured vs 100% Billed',
              summary: 'Only 14% of billing is captured — trace the remaining 86%',
              content: 'Invoice shows 8.51 GB; pipeline meter shows 1.23 GB. The 7.28 GB residual is decomposed into browser, unmeasured scripts, and Studio traffic.',
              result: '86% residual confirmed — principle established: never blame a single cause.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['Supabase'],
              created_at: '2026-09-02',
              status: 'in_progress',
            },
            {
              id: 'card-28',
              title: 'Frontend Query Byte Reproduction',
              summary: 'Replicate browser queries with curl to measure egress directly',
              content: 'PublicBoard and Dashboard queries were replicated column-for-column with gzip headers attached. select(*) came out at 395 KB per visitor.',
              result: '1 dashboard open = 13.9 MB warm / 23.3 MB cold.',
              mindsetTags: ['Validation Discipline', 'Autonomous Execution'],
              toolTags: ['Supabase', 'PostgreSQL'],
              created_at: '2026-09-01',
              status: 'completed',
            },
            {
              id: 'card-29',
              title: 'Billing Unit: gzip vs Raw',
              summary: 'Determine whether billing counts compressed or raw bytes',
              content: 'Isolated 8/26 (scrape-only day) and compared measured vs billed bytes. Raw byte assumption makes the arithmetic physically impossible → billing is post-compression.',
              result: '8/26: measured 78.2 MB / billed 108.6 MB → gzip billing confirmed.',
              mindsetTags: ['Validation Discipline', 'Self-Error Correction'],
              toolTags: ['Supabase'],
              created_at: '2026-08-31',
              status: 'completed',
            },
            {
              id: 'card-30',
              title: 'Public Board Static Snapshot Migration',
              summary: 'Reduce per-visitor egress from 395 KB to zero',
              content: 'Started migrating the public board from live PostgREST calls to static snapshots. Goal is to eliminate visitor-driven egress entirely.',
              result: '395 KB → 0 target set; migration in progress.',
              mindsetTags: ['Cost Awareness', 'Autonomous Execution'],
              toolTags: ['Supabase', 'Next.js'],
              created_at: '2026-08-30',
              status: 'in_progress',
            },
            {
              id: 'card-31',
              title: 'Polling Interval 5s → 30s',
              summary: 'Daemon polling creates a floor egress — extend the interval',
              content: '5-second polling at 17,280 calls/day generates a 960 B floor per call. Extending to 30 seconds reduces polling egress to 1/6.',
              result: '9/1: pipeline 0, but 11.6 MB present → floor confirmed as polling → interval extended.',
              mindsetTags: ['Cost Awareness', 'Validation Discipline'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-29',
              status: 'in_progress',
            },
            {
              id: 'card-32',
              title: 'fetchEvaluations Column Projection',
              summary: 'Reduce 13 MB query to ~1.5 MB by selecting only needed columns',
              content: 'Changed select(*) over 19,714 heavy JSON rows to project only needed columns.',
              result: 'fetchEvaluations 13.0 MB → ~1.5 MB target; projection work started.',
              mindsetTags: ['Cost Awareness', 'Self-Error Correction'],
              toolTags: ['PostgreSQL', 'Supabase'],
              created_at: '2026-08-28',
              status: 'in_progress',
            },
            {
              id: 'card-33',
              title: 'Self-Consuming Cost Monitor',
              summary: 'Opening /admin generates 14 MB egress — the monitor eats itself',
              content: 'Identified that viewing the cost dashboard generates additional egress. Policy updated: the monitoring screen reads only static figures.',
              result: '/admin open = 14 MB — self-consumption documented; policy changed.',
              mindsetTags: ['Self-Error Correction', 'Cost Awareness'],
              toolTags: ['Supabase'],
              created_at: '2026-08-27',
              status: 'blocked',
            },
          ],
        },
        {
          id: 'goal-db-perf',
          title: 'DB Performance',
          description: 'Measure and improve query speed based on real profiling',
          cards: [
            {
              id: 'card-34',
              title: 'Slow Query Profiling',
              summary: 'Identify bottleneck queries with EXPLAIN ANALYZE',
              content: 'Enabled slow query log and ran EXPLAIN ANALYZE on top queries to locate full-scan points.',
              result: '3 of top 5 queries were seq scans → index candidates identified.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-26',
              status: 'completed',
            },
            {
              id: 'card-35',
              title: 'Composite Index Addition (−23% Query Cost)',
              summary: 'Add composite index on frequently filtered columns',
              content: 'Added composite indexes on seq-scan queries and compared cost before and after. Write overhead was also measured.',
              result: 'Target query average cost −23% (EXPLAIN comparison).',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-25',
              status: 'completed',
            },
            {
              id: 'card-36',
              title: 'N+1 Elimination (−40% Query Count)',
              summary: 'Replace repeated single-row fetches with JOIN and batch loading',
              content: 'Replaced per-row extra queries in list renders with JOIN and batch loading.',
              result: 'Query count per page reduced by 40% — confirmed.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-24',
              status: 'completed',
            },
            {
              id: 'card-37',
              title: 'Redis Cache for Aggregates',
              summary: 'Cache frequently queried aggregates with a defined invalidation rule',
              content: 'Cached stable aggregate results in Redis with an invalidation policy. Cache hit rate is logged.',
              result: 'Hot aggregate cache hit tracking started — DB load reduction observed.',
              mindsetTags: ['Cost Awareness', 'Autonomous Execution'],
              toolTags: ['Redis', 'PostgreSQL'],
              created_at: '2026-08-23',
              status: 'in_progress',
            },
            {
              id: 'card-38',
              title: 'Monthly Partition Design',
              summary: 'Partition large tables by month for write-skewed access patterns',
              content: 'Designed monthly partitioning based on the observation that queries concentrate on recent data. Old partitions are cold storage candidates.',
              result: 'Reduced scan range on recent partitions — design finalised.',
              mindsetTags: ['Validation Discipline'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-22',
              status: 'in_progress',
            },
            {
              id: 'card-39',
              title: 'Connection Pooling (PgBouncer)',
              summary: 'Cap concurrent connections to reduce cost and instability',
              content: 'PgBouncer deployed in transaction mode to reuse connections.',
              result: 'Connection cap applied; peak connection exhaustion eliminated.',
              mindsetTags: ['Cost Awareness', 'Self-Error Correction'],
              toolTags: ['PostgreSQL', 'Docker'],
              created_at: '2026-08-21',
              status: 'in_progress',
            },
          ],
        },
        {
          id: 'goal-auth-sec',
          title: 'Auth & Security',
          description: 'Control access with tokens, RLS, and rate limiting',
          cards: [
            {
              id: 'card-40',
              title: 'JWT Access / Refresh Token Split',
              summary: 'Short-lived access tokens; silent renewal via refresh',
              content: 'Set a short expiry for access tokens and added a silent refresh flow. Expiry and re-issuance paths were verified end-to-end.',
              result: 'Auto-renewal after token expiry verified.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['Supabase', 'end-to-end'],
              created_at: '2026-08-20',
              status: 'completed',
            },
            {
              id: 'card-41',
              title: 'Row-Level Security (RLS) Audit',
              summary: 'Review per-user access policies and reduce anon key surface',
              content: 'Reviewed all RLS policies case by case and narrowed the surface reachable with the anon key.',
              result: 'Anon-accessible surface reduced; policy gaps listed.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['Supabase', 'PostgreSQL'],
              created_at: '2026-08-19',
              status: 'in_progress',
            },
            {
              id: 'card-42',
              title: 'API Rate Limiting',
              summary: 'Per-user per-hour request cap',
              content: 'Added user- and IP-level rate limiting to prevent abuse and polling spikes.',
              result: 'Over-limit requests return 429 — verified.',
              mindsetTags: ['Cost Awareness', 'Autonomous Execution'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-18',
              status: 'in_progress',
            },
            {
              id: 'card-43',
              title: 'Service Key Exposure Audit',
              summary: 'Remove any service key usage from the frontend bundle',
              content: 'Grepped the frontend bundle for service key usage and forced all calls through the anon path.',
              result: 'Zero service key strings in bundle — confirmed.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['Supabase', 'Next.js'],
              created_at: '2026-08-17',
              status: 'completed',
            },
            {
              id: 'card-44',
              title: 'Audit Log Collection',
              summary: 'Audit trail for sensitive operations',
              content: 'Added triggers to log permission changes and deletions.',
              result: 'Audit logs recorded for 3 sensitive operation types.',
              mindsetTags: ['Execution over Docs', 'Autonomous Execution'],
              toolTags: ['PostgreSQL'],
              created_at: '2026-08-16',
              status: 'in_progress',
            },
            {
              id: 'card-45',
              title: 'Secret Migration to Env Vars',
              summary: 'Move hardcoded keys to .env / secret manager',
              content: 'Moved remaining hardcoded keys to environment variables or a secret manager and documented the rotation procedure.',
              result: 'Zero hardcoded secrets; rotation procedure recorded.',
              mindsetTags: ['Validation Discipline', 'Self-Error Correction'],
              toolTags: ['Docker'],
              created_at: '2026-08-15',
              status: 'completed',
            },
          ],
        },
      ],
    },
    {
      id: 'project-llm-evals',
      title: 'LLM Evaluation & Optimisation',
      description: 'Benchmark, fine-tune, and serve models driven by measurement',
      goals: [
        {
          id: 'goal-benchmark',
          title: 'Model Benchmark System',
          description: 'Run standard benchmarks automatically and compare cost-performance',
          cards: [
            {
              id: 'card-46',
              title: 'lm-eval-harness Integration',
              summary: 'Run MMLU, GSM8K, and other standard benchmarks automatically',
              content: 'Attached harness to the pipeline to run model × task combinations in one shot and persist results.',
              result: 'MMLU and GSM8K run automatically and results are stored.',
              mindsetTags: ['Execution over Docs', 'Validation Discipline'],
              toolTags: ['lm-eval-harness'],
              created_at: '2026-08-30',
              status: 'completed',
              evidence: [{ label: 'Benchmark results spreadsheet', url: 'https://docs.google.com/spreadsheets/example', type: 'doc' }],
            },
            {
              id: 'card-47',
              title: 'Claude / GPT-4 / Llama-2 Comparison',
              summary: 'Score response quality with a shared prompt set',
              content: 'Ran the same prompt set through three models and scored accuracy and format compliance.',
              result: 'Accuracy table across three models captured — per-task ranking separated.',
              mindsetTags: ['Validation Discipline', 'Cost Awareness'],
              toolTags: ['lm-eval-harness'],
              created_at: '2026-08-28',
              status: 'completed',
            },
            {
              id: 'card-48',
              title: 'Cost-Performance Chart',
              summary: 'Scatter plot of token price vs accuracy to find Pareto candidates',
              content: 'Plotted per-model token cost against benchmark accuracy on a single plane to identify the Pareto frontier.',
              result: 'Cost-accuracy scatter produced — low-cost high-accuracy candidates identified.',
              mindsetTags: ['Cost Awareness', 'Validation Discipline'],
              toolTags: ['lm-eval-harness', 'Next.js'],
              created_at: '2026-08-26',
              status: 'in_progress',
            },
            {
              id: 'card-49',
              title: 'Custom Evaluation Metric',
              summary: 'Execution-based code accuracy scorer for domain tasks',
              content: 'Replaced string-match with an execution-based correctness metric. Scoring runs in a sandboxed environment.',
              result: 'Execution-based scoring applied to code tasks — confirmed.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['lm-eval-harness', 'Docker'],
              created_at: '2026-08-24',
              status: 'in_progress',
            },
            {
              id: 'card-50',
              title: 'Monthly Benchmark Report Automation',
              summary: 'Auto-aggregate performance trends and notify via Slack monthly',
              content: 'Harness results are collected monthly into a trend table and sent to Slack.',
              result: 'First monthly trend report generated automatically.',
              mindsetTags: ['Autonomous Execution', 'Execution over Docs'],
              toolTags: ['lm-eval-harness'],
              created_at: '2026-08-22',
              status: 'in_progress',
            },
            {
              id: 'card-51',
              title: 'A/B Statistical Significance Framework',
              summary: 'Test whether the difference between two models is statistically significant',
              content: 'Built a framework for collecting preference ratings and testing significance between two models.',
              result: 'Insufficient sample size for significance — collection ongoing (blocked).',
              mindsetTags: ['Validation Discipline', 'Autonomous Execution'],
              toolTags: ['lm-eval-harness'],
              created_at: '2026-08-20',
              status: 'blocked',
            },
          ],
        },
        {
          id: 'goal-finetune',
          title: 'Fine-tuning & Optimisation',
          description: 'Customise and compress models for specific tasks',
          cards: [
            {
              id: 'card-52',
              title: 'Training Data Curation',
              summary: 'Curate 500 code-generation examples',
              content: 'Filtered duplicates and low-quality examples to produce 500 curated code-generation training pairs. Licences were also reviewed.',
              result: 'Post-curation: 500 examples confirmed; deduplication rate recorded.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['LoRA'],
              created_at: '2026-08-25',
              status: 'completed',
            },
            {
              id: 'card-53',
              title: 'LoRA Fine-tuning Experiment',
              summary: 'Apply LoRA adapter to Llama-2 and track the learning curve',
              content: 'Ran low-cost fine-tuning with a LoRA adapter and tracked the loss curve.',
              result: 'Training loss converged; overfit signs are being monitored.',
              mindsetTags: ['Self-Error Correction', 'Validation Discipline'],
              toolTags: ['LoRA'],
              created_at: '2026-08-23',
              status: 'in_progress',
            },
            {
              id: 'card-54',
              title: 'Hyperparameter Grid Search',
              summary: 'Optimise learning rate, batch size, and epoch count',
              content: 'Swept three key hyperparameters on a small grid and selected by validation loss. Pre-set cost ceiling enforced.',
              result: 'Minimum validation loss combination found within cost ceiling.',
              mindsetTags: ['Cost Awareness', 'Validation Discipline'],
              toolTags: ['LoRA'],
              created_at: '2026-08-21',
              status: 'in_progress',
            },
            {
              id: 'card-55',
              title: 'Fine-tuned vs Baseline Comparison',
              summary: 'BLEU / ROUGE scoring on a held-out test set',
              content: 'Scored the fine-tuned model against the baseline on the same test set to measure uplift.',
              result: 'Score improvement over baseline confirmed on target tasks.',
              mindsetTags: ['Validation Discipline', 'Execution over Docs'],
              toolTags: ['lm-eval-harness', 'LoRA'],
              created_at: '2026-08-19',
              status: 'in_progress',
            },
            {
              id: 'card-56',
              title: '4-bit Quantisation (−30% Model Size)',
              summary: 'Quantise for reduced deployment footprint',
              content: 'Applied 4-bit quantisation and measured accuracy loss alongside size and speed gains.',
              result: 'Model size −30%; accuracy loss within acceptable range.',
              mindsetTags: ['Cost Awareness', 'Self-Error Correction'],
              toolTags: ['vLLM', 'LoRA'],
              created_at: '2026-08-17',
              status: 'in_progress',
            },
            {
              id: 'card-57',
              title: 'Inference Latency Profile',
              summary: 'Measure tokens/s and TTFT bottlenecks',
              content: 'Measured TTFT and throughput across batch size and sequence length to identify the bottleneck.',
              result: 'Throughput-vs-batch curve captured; optimal batch window identified.',
              mindsetTags: ['Validation Discipline', 'Cost Awareness'],
              toolTags: ['vLLM'],
              created_at: '2026-08-16',
              status: 'completed',
            },
          ],
        },
        {
          id: 'goal-serve',
          title: 'Deployment & Monitoring',
          description: 'Configure production serving and performance monitoring',
          cards: [
            {
              id: 'card-58',
              title: 'vLLM Server Setup',
              summary: 'Deploy GPU-optimised inference server',
              content: 'Deployed a continuous batching server with vLLM and tripled concurrency vs the previous setup.',
              result: '3× concurrency increase — startup confirmed.',
              mindsetTags: ['Validation Discipline', 'Autonomous Execution'],
              toolTags: ['vLLM', 'Docker'],
              created_at: '2026-08-30',
              status: 'completed',
              evidence: [
                { label: 'Deployment config', url: 'https://github.com/example/gstack/blob/main/vllm.yaml', type: 'github' },
              ],
            },
            {
              id: 'card-59',
              title: 'OpenAI-Compatible API Wrapper',
              summary: 'Expose vLLM endpoint in OpenAI schema for zero-change client adoption',
              content: 'Wrapped the vLLM endpoint in an OpenAI-compatible schema so existing clients attach without modification.',
              result: 'Existing SDK calls succeed unchanged.',
              mindsetTags: ['Execution over Docs', 'Autonomous Execution'],
              toolTags: ['vLLM', 'end-to-end'],
              created_at: '2026-08-28',
              status: 'completed',
            },
            {
              id: 'card-60',
              title: 'Real-time Performance Dashboard',
              summary: 'Track tokens/s, response time, and GPU memory',
              content: 'Serving metrics are collected in real time and displayed on a dashboard. Threshold breaches are highlighted.',
              result: 'Three core metrics updating in real time.',
              mindsetTags: ['Validation Discipline', 'Cost Awareness'],
              toolTags: ['vLLM', 'Next.js'],
              created_at: '2026-08-26',
              status: 'in_progress',
            },
            {
              id: 'card-61',
              title: 'Automatic Rollback on Error Rate Threshold',
              summary: 'Auto-revert to previous version when error rate exceeds 5%',
              content: 'Added a hook that automatically reverts the deployment when error rate crosses the threshold.',
              result: 'Auto-rollback triggered on synthetic fault injection.',
              mindsetTags: ['Self-Error Correction', 'Autonomous Execution'],
              toolTags: ['Docker', 'end-to-end'],
              created_at: '2026-08-24',
              status: 'in_progress',
            },
            {
              id: 'card-62',
              title: 'Kubernetes Autoscaling',
              summary: 'Scale inference replicas automatically under load',
              content: 'HPA configured with throughput-based scaling; cold-start latency mitigated.',
              result: 'Replicas scale out on load increase — verified.',
              mindsetTags: ['Autonomous Execution', 'Cost Awareness'],
              toolTags: ['Docker'],
              created_at: '2026-08-22',
              status: 'in_progress',
            },
            {
              id: 'card-63',
              title: 'Deployment Version Tracking',
              summary: 'Record benchmark scores and serving metrics per model version',
              content: 'Each version stores benchmark scores and serving metrics together as rollback evidence.',
              result: 'Per-version performance records stored; rollback path verified.',
              mindsetTags: ['Validation Discipline', 'Self-Error Correction'],
              toolTags: ['Docker', 'lm-eval-harness'],
              created_at: '2026-08-20',
              status: 'in_progress',
            },
            {
              id: 'card-64',
              title: 'User Feedback Loop',
              summary: 'Route thumbs-up/down ratings into retraining data',
              content: 'Response ratings are collected and piped into the retraining candidate dataset.',
              result: 'Feedback → dataset ingestion path succeeded once end-to-end.',
              mindsetTags: ['Execution over Docs', 'Autonomous Execution'],
              toolTags: ['end-to-end', 'LoRA'],
              created_at: '2026-08-18',
              status: 'in_progress',
            },
          ],
        },
      ],
    },
  ],
};
